toolchain

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -1,6 +1,6 @@
 ---
 stages:
-- name: Build Stage
+- name: BUILD
   inputs:
   - type: git
     branch: master
@@ -9,19 +9,18 @@ stages:
   jobs:
   - name: Build
     type: builder
-    artifact_dir: ''
-- name: Deploy Stage
+- name: DEPLOY
   inputs:
   - type: job
-    stage: Build Stage
+    stage: BUILD
     job: Build
   triggers:
   - type: stage
   jobs:
-  - name: Deploy to dev
+  - name: Deploy sample application
     type: deployer
     target:
-      url: ${CF_TARGET_URL}
+      region_id: ${CF_REGION_ID}
       organization: ${CF_ORGANIZATION}
       space: ${CF_SPACE}
       application: ${CF_APP}
@@ -31,11 +30,10 @@ stages:
       echo organization "${CF_ORGANIZATION}"
       echo space "${CF_SPACE}"
       echo url "${CF_TARGET_URL}"
-      serviceId=`echo ${CF_APP} | tail -c 37`
-      echo serviceId "${serviceId}"
+      echo serviceId "${BIND_TO}"
       serviceJson=`cf curl /v2/service_instances/${serviceId}`
       echo serviceJson "${serviceJson}"
-      errorCode=`echo ${serviceJson} | grep -Po '(?<="error_code": ")[^"]*' || true` 
+      errorCode=`echo ${serviceJson} | grep -Po '(?<="error_code": ")[^"]*' || true`
       echo errorCode ${errorCode}
       if [[ -z $errorCode ]]
       then
@@ -45,7 +43,7 @@ stages:
        then
         serviceInfo=`cf service "${serviceName}" || true`
         echo serviceInfo "${serviceInfo}"
-        serviceLabel=`echo ${serviceInfo} | awk '{for (I=1;I<=NF;I++) if ($I == "Service:") {print $(I+1)};}'` 
+        serviceLabel=`echo ${serviceInfo} | awk '{for (I=1;I<=NF;I++) if ($I == "Service:") {print $(I+1)};}'`
         echo serviceLabel "${serviceLabel}"
         if [[ ! -z $serviceLabel ]]
         then
@@ -55,10 +53,10 @@ stages:
          sed -i "$ a \    PA_SERVICE_LABEL: ${serviceLabel}" manifest.yml
         else
          echo "The problem occured when retrieving the serviceLabel. The service will not be bound to the app."
-        fi 
+        fi
        else
          echo "The problem occured when retrieving the serviceName. The service will not be bound to the app."
-       fi 
+       fi
       else
         echo "The problem occured when retrieving the serviceName. The service will not be bound to the app."
       fi
